export const API_URL = {
  HOME: {
      SUCCESS_VIDEOS: '/api/video/',
      ADD_SUCCESS_VIDEO: '/api/video/',
      DELETE_SUCCESS_VIDEO: (id: string) => `/api/video/${id}/`,
      UPDATE_SUCCESS_VIDEO: (id: string) => `/api/video/${id}/`,
      GET_REVIEWS: '/api/student-review/',
      ADD_REVIEW: '/api/student-review/',
      DELETE_REVIEW: (id: string) => `/api/student-review/${id}/`,
      UPDATE_REVIEW: (id: string) => `/api/student-review/${id}/`,
      REVIEWS: '/api/student-review/',
  },
  SERVICES: {
      GET_SERVICE_HEADING: '/api/service-header/',
      CREATE_SERVICE_HEADING: '/api/service-header/',
      PATCH_SERVICE_HEADING: (id: string) => `/api/service-header/${id}/`,
      DELETE_SERVICE_HEADING: (id: string) => `/api/service-header/${id}/`,
      GET_SERVICE_DETAILS: '/api/service-body/',
      CREATE_SERVICE_DETAILS: '/api/service-body/',
      PATCH_SERVICE_DETAILS: (id: string) => `/api/service-body/${id}/`,
      DELETE_SERVICE_DETAILS: (id: string) => `/api/service-body/${id}/`,
  },
  BLOGS: {
      POST_BLOG_CATEGORIES: '/api/blog-category/',
      GET_BLOG_CATEGORIES: '/api/blog-category/',
      PATCH_BLOG_CATEGORY: (id: string) => `/api/blog-category/${id}/`,
      DELETE_BLOG_CATEGORY: (id: string) => `/api/blog-category/${id}/`,
      GET_BLOG_HEADERS: '/api/blog-heading/',
      POST_BLOG_HEADERS: '/api/blog-heading/',
      PATCH_BLOG_HEADERS: (id: string) => `/api/blog-heading/${id}/`,
      DELETE_BLOG_HEADERS: (id: string) => `/api/blog-heading/${id}/`,
      GET_BLOGS: '/api/blogs/',
      POST_BLOGS: '/api/blogs/',
      PATCH_BLOGS: (id: string) => `/api/blogs/${id}/`,
      DELETE_BLOGS: (id: string) => `/api/blogs/${id}/`,
  },
  BLOG_INNER: {
    GET_BLOG_INNER: '/api/blog-inner/',
    POST_BLOG_INNER: '/api/blog-inner/',
    PATCH_BLOG_INNER: (id: string) => `/api/blog-inner/${id}/`,
    DELETE_BLOG_INNER: (id: number) => `/api/blog-inner/${id}/`,
  },
  COUNTRIES: {
    GET_COUNTRIES: '/api/countries/',
    POST_COUNTRY: '/api/countries/',
    PATCH_COUNTRY: (id: number | string) => `/api/countries/${id}/`,
    DELETE_COUNTRY: (id: number | string) => `/api/countries/${id}/`,
  },
  UNIVERSITIES: {
    GET_UNIVERSITIES: '/api/university/',
    POST_UNIVERSITY: '/api/university/',
    PATCH_UNIVERSITY: (id: number | string) => `/api/university/${id}/`,
    DELETE_UNIVERSITY: (id: number | string) => `/api/university/${id}/`,
  },
  WHY_CHOOSE_REASONS: {
    GET_WHY_CHOOSE_REASONS: '/api/why-choose/',
    POST_WHY_CHOOSE_REASON: '/api/why-choose/',
    PATCH_WHY_CHOOSE_REASON: (id: number | string) => `/api/why-choose/${id}/`,
    DELETE_WHY_CHOOSE_REASON: (id: number | string) => `/api/why-choose/${id}/`,
  },
  CONTACT: {
    GET_CONTACT: '/api/contact/',
    POST_CONTACT: '/api/contact/',
    PATCH_CONTACT: (id: number | string) => `/api/contact/${id}/`,
    DELETE_CONTACT: (id: number | string) => `/api/contact/${id}/`,
  },  
  SEO: {
    HOME_SEO: '/api/MetaTagsHome/',
    BLOG_SEO: '/api/blogmeta/',
    CONTACT_SEO: '/api/contactmeta/',
    STUDY_ABROAD_SEO: '/api/countrymeta/',
    SERVICE_SEO: '/api/servicemeta/',
},
}